services:
  - type: web
    name: foodplease-backend
    env: docker
    repo: https://github.com/stevedch/foodplease-backend
    branch: main
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: R2DBC_DATABASE_URL
        fromDatabase:
          name: unab
          property: connectionString