spring:
  r2dbc:
    url: ${R2DBC_DATABASE_URL}
  main:
    web-application-type: reactive
  application:
    name: foodplease-backend

flyway:
  enabled: false

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO