server:
  port: ${PORT:8080}

spring:
  r2dbc:
    url: ${R2DBC_DATABASE_URL:r2dbc:postgresql://localhost:5432/dummy}
  main:
    web-application-type: reactive
  application:
    name: foodplease-backend