spring:
  r2dbc:
    url: ${R2DBC_DATABASE_URL}
  main:
    web-application-type: reactive
  application:
    name: foodplease-backend

# Optional: disables Flyway if you're not using it
flyway:
  enabled: false

logging:
  level:
    root: INFO